version: 2

models:
  - name: stg_superheroes
    description: Demographics about each superhero such as name, hair color, height and weight.
    columns:
      - name: name
        tests:
          - not_null
      - name: height
        tests:
          - positive_values
      - name: weight_lbs
        tests:
          - positive_values
  - name: stg_users 
    columns:
      - name: user_guid
        description: Unique string guid for each customer.
        tests:
          - unique